apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis
    role: worker
    tier: backend
  name: rq-worker-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: worker
      tier: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
        role: worker
        tier: backend
    spec:
      containers:
      - env:
        - name: GET_HOSTS_FROM
          value: dns
        image: castrona/rq-worker:2
        name: rq-worker
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
status: {}
