services:
  api:
    platform: linux/amd64
    image: api
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - ./api/com_res:/com_res
      # https://cloud.google.com/docs/authentication/external/set-up-adc
      - $HOME/.config/gcloud/application_default_credentials.json:/app/key.json
    build:
      context: ./api/
      dockerfile: Dockerfile
    working_dir: /com_res
    command: uvicorn --host 0.0.0.0 --port 8000 --proxy-headers main:app
    env_file:
      - .env
