volumes:
  mongo_data:
    driver: local

services:
  caddy:
    image: caddy
    build:
      dockerfile: Dockerfile
      context: ./caddy/
    volumes:
      - ./caddy:/etc/caddy
    ports:
      - 443:443
      - 80:80
    depends_on:
      - api
    restart: unless-stopped

  api:
    image: api
    ports:
      - 8000:8000
      - 5678:5678
      - 8181:8181
    restart: unless-stopped
    volumes:
      - ./api/com_res:/com_res
      - /Users/dcowan/.config/gcloud/application_default_credentials.json:/app/key.json
    build:
      context: ./api/
      dockerfile: Dockerfile
    working_dir: /com_res
    command: python -m debugpy --listen 0.0.0.0:5678 -m uvicorn --host 0.0.0.0 --port 8000 --proxy-headers main:app --reload
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
