metadata:
  name: metadata-extractor-path
  namespace: workflows
spec:
  templates:
    - name: metadata-extractor
      inputs:
        parameters:
          - name: bucket
            value: '{{workflow.parameters.bucket}}'
          - name: input-path
            value: '{{workflow.parameters.input-path}}'
          - name: output-path
            value: '{{workflow.parameters.output-path}}'
          - name: base-url
            value: '{{workflow.parameters.base-url}}'
        artifacts:
          - name: input-data
            path: /tmp/resource
            s3:
              endpoint: api.minio.cuahsi.io
              bucket: '{{inputs.parameters.bucket}}'
              accessKeySecret:
                name: minio-credentials
                key: accessKey
              secretKeySecret:
                name: minio-credentials
                key: secretKey
              key: '{{inputs.parameters.input-path}}'
      outputs:
        artifacts:
          - name: output-metadata
            path: /tmp/resource/.hs
            s3:
              endpoint: api.minio.cuahsi.io
              bucket: '{{inputs.parameters.bucket}}'
              accessKeySecret:
                name: minio-credentials
                key: accessKey
              secretKeySecret:
                name: minio-credentials
                key: secretKey
              key: '{{inputs.parameters.output-path}}'
            archive:
              none: {}
      metadata: {}
      container:
        name: ''
        image: scootna/hsextract:0.4.7
        command:
          - /bin/sh
          - '-c'
        args:
          - >-
            python3 hsextract/main.py extract /tmp/resource {{inputs.parameters.base-url}}
        resources: {}
  entrypoint: metadata-extractor
  arguments:
    parameters:
      - name: bucket
      - name: input-path
      - name: output-path
      - name: base-url
  templateDefaults:
    inputs: {}
    outputs: {}
    metadata: {}
    retryStrategy:
      limit: '0'
    timeout: 3600s
