metadata:
  name: collect-aorc-forcing-v1.2
  namespace: workflows
spec:
  templates:
    - name: collect-aorc
      inputs:
        parameters:
        - name: shape-file-path
          value: '{{workflow.parameters.shape-file-path}}'
        - name: output-path
          value: '{{workflow.parameters.output_path}}'
        - name: start-date
          value: '{{workflow.parameters.start-date}}'
        - name: end-date
          value: '{{workflow.parameters.end-date}}'
        - name: aorc-secret
          value: '{{workflow.parameters.aorc-secret}}'
        - name: output-bucket
          value: '{{workflow.parameters.output-bucket}}'
        artifacts:
          - name: shapefile-input
            path: /srv/shp-data
            s3:
              endpoint: api.minio.cuahsi.io
              bucket: '{{inputs.parameters.output-bucket}}'
              accessKeySecret:
                name: minio-credentials
                key: accessKey
              secretKeySecret:
                name: minio-credentials
                key: secretKey
              key: '{{inputs.parameters.shape-file-path}}'
      outputs:
        artifacts:
          - name: aorc-output-artifact
            path: /output
            archive:
              none: {}
            s3:
              endpoint: api.minio.cuahsi.io
              bucket: '{{inputs.parameters.output-bucket}}'
              accessKeySecret:
                name: minio-credentials
                key: accessKey
              secretKeySecret:
                name: minio-credentials
                key: secretKey
              key: '{{inputs.parameters.output-path}}/aorc_output.gz'
      metadata: {}
      container:
        image: us-central1-docker.pkg.dev/apps-320517/subsetter/aorc:0.0.2
        env:
          - name: KEY
            value: AKIATL6IACWUADAFYDMC
          - name: SECRET
            value: "{{inputs.parameters.aorc-secret}}"
          - name: BUCKET_URL
            value: s3://aorc-v1.1-zarr-1-year/
          - name: SHAPE_FILE
            value: /srv/shp-data/watershed.shp
          - name: START_DATE
            value: "{{inputs.parameters.start-date}}"
          - name: END_DATE
            value: "{{inputs.parameters.end-date}}"
          - name: OUTPUT_FILE
            value: /output/results.nc
          - name: N_WORKERS
            value: '2'
          - name: MEMORY_LIMIT
            value: 4GB
        command:
          - /bin/sh
          - '-c'
        args:
          - >-
            python /app/collect-aorc-forcing-v1.1.py
        ports:
          - containerPort: 8787
        resources:
          requests:
            cpu: '2'
            ephemeral-storage: 10Gi
            memory: 16Gi
  entrypoint: collect-aorc
  arguments:
    parameters:
      - name: start-date
        value: '2020-01-01'
      - name: end-date
        value: '2020-01-2'
      - name: output-bucket
        value: subsetter_outputs
      - name: output_path
        value: sblack/qwerty
      - name: shape-file-path
        value: qwerty/shape.gz
      - name: aorc-secret
        value: changethis/zuFe6XApPIZrbnKWfliP
  templateDefaults:
    inputs: {}
    outputs: {}
    metadata: {}
    retryStrategy:
      limit: '0'
    timeout: 600s

