version: "3.3"
services:
  subsetter:
    image: subsetter:latest
    build:
      context: .
      dockerfile: Dockerfile.subsetter
    environment: 
      PYTHONWARNINGS: "ignore:Unverified HTTPS request"
      GDAL_DATA: "/root/miniconda3/share/gdal"
      PROJ_LIB: "/root/miniconda3/share/proj"
    ports: 
      - "80:80"
    expose:
      - "80"
    volumes:
      - /share:/share
  redis:
    image: redis:alpine
    expose:
      - "6379"

