version: "3.3"
services:
  app:
    image: cuahsi/subsetter-ubuntu:0.1
    build:
      context: ..
      #dockerfile: docker/Dockerfile.subsetter
      dockerfile: docker/Dockerfile.ubuntu
    environment: 
      PYTHONWARNINGS: "ignore:Unverified HTTPS request"
      GDAL_DATA: "/opt/miniconda/share/gdal"
      PROJ_LIB: "/opt/miniconda/share/proj"
      PORT: 8888
      REDIS_URL: redis_db
      REDIS_PORT: 6379
      PF_EXE_DIR: /usr/local
      SSL_CERT: /srv/ssl/wildcard_cuahsi_org.crt
      SSL_KEY: /srv/ssl/wildcard_cuahsi_org.key
    ports: 
      - "443:8888"
    expose:
      - "443"
    volumes:
      - ./share:/share
      - ../tornado-app:/srv
    links:
      - redis_db
  redis_db:
    image: redis:alpine
    ports:
      - "6379:6379"
    expose:
      - "6379"
