version: "3.3"
services:
  app:
    image: subsetter-ubuntu:latest
    build:
      context: ..
      #dockerfile: docker/Dockerfile.subsetter
      dockerfile: docker/Dockerfile.ubuntu
    environment: 
      PYTHONWARNINGS: "ignore:Unverified HTTPS request"
      GDAL_DATA: "/opt/miniconda/share/gdal"
      PROJ_LIB: "/opt/miniconda/share/proj"
      PORT: 8888
      REDIS_URL: redis_db
      REDIS_PORT: 6379
      PF_EXE_DIR: /usr/local
      SSL_CERT: ssl/wildcard_cuahsi_org.cert
      SSL_KEY: ssl/wildcard_cuahsi_org.key

    ports: 
      - "80:8888"
    expose:
      - "80"
    volumes:
#      - ./share:/share
      - /Volumes/ColdStorage/subsetter/domain-data/:/share
      - ../tornado-app:/srv
    links:
      - redis_db
  redis_db:
    image: redis:alpine
    ports:
      - "6379:6379"
    expose:
      - "6379"
