version: "3.3"
services:
  app:
    image: subsetter:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile.subsetter
    environment: 
      PYTHONWARNINGS: "ignore:Unverified HTTPS request"
      GDAL_DATA: "/root/miniconda3/share/gdal"
      PROJ_LIB: "/root/miniconda3/share/proj"
      PORT: '8888'
    ports: 
      - "80:8888"
    expose:
      - "80"
    volumes:
      #      - /share:/share
      - ../tornado-app:/srv
  redis:
    image: redis:alpine
    expose:
      - "6379"
