metadata:
  name: parflow-subset-v1-by-huc-minio
  namespace: workflows
spec:
  templates:
    - name: parflow-subset-huc
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: huc-to-shp
            templateRef:
              name: huc-to-shp
              template: huc-to-shp
            arguments:
              parameters:
                - name: output-path
                  value: '{{workflow.parameters.output-path}}'
                - name: output-bucket
                  value: '{{workflow.parameters.output-bucket}}'
                - name: hucs
                  value: '{{workflow.parameters.hucs}}'
        - - name: subset-parflow
            template: parflow-subset-v1
            arguments:
              parameters:
                - name: label
                  value: '{{workflow.parameters.label}}'
                - name: output-path
                  value: '{{workflow.parameters.output-path}}'
                - name: output-bucket
                  value: '{{workflow.parameters.output-bucket}}'
        - - name: metadata-extraction
            templateRef:
              name: metadata-extractor
              template: metadata-extractor
            arguments:
              parameters:
                - name: bucket
                  value: '{{workflow.parameters.output-bucket}}'
                - name: input-path
                  value: '{{workflow.parameters.output-path}}'
                - name: output-path
                  value: '{{workflow.parameters.output-path}}/hs_metadata.tgz'
    - name: parflow-subset-v1
      inputs:
        parameters:
          - name: label
          - name: output-path
          - name: output-bucket
        artifacts:
          - name: shape-input-data
            path: /srv/shape
            s3:
              endpoint: api.minio.cuahsi.io
              bucket: '{{inputs.parameters.output-bucket}}'
              accessKeySecret:
                name: minio-credentials
                key: accessKey
              secretKeySecret:
                name: minio-credentials
                key: secretKey
              key: '{{inputs.parameters.output-path}}'
      outputs:
        artifacts:
          - name: subset-results
            path: /srv/shape
            s3:
              endpoint: api.minio.cuahsi.io
              bucket: '{{inputs.parameters.output-bucket}}'
              accessKeySecret:
                name: minio-credentials
                key: accessKey
              secretKeySecret:
                name: minio-credentials
                key: secretKey
              key: '{{inputs.parameters.output-path}}'
      metadata: {}
      container:
        name: ''
        image: cuahsi/parflow-subset-argo:v1
        command:
          - python
          - '-u'
          - entry.py
        args:
          - '{{inputs.parameters.label}}'
          - /srv/shape/watershed.shp
          - /srv/input/pfconus.v1.0/input
          - /srv/shape
        resources:
          limits:
            cpu: '2'
            ephemeral-storage: 2Gi
            memory: 1Gi
          requests:
            cpu: '1'
            ephemeral-storage: 1Gi
            memory: 1Gi
        volumeMounts:
          - name: subsetter-data-volume
            mountPath: /srv/input
  entrypoint: parflow-subset-huc
  arguments:
    parameters:
      - name: label
        value: pf-subset-job
      - name: output-path
        value: abc123
      - name: output-bucket
        value: subsetter-outputs
      - name: hucs
        value: 102600070103,102600070104,102600090205,102600050206,102600070102
  volumes:
    - name: subsetter-data-volume
      persistentVolumeClaim:
        claimName: subset-accelerator
  templateDefaults:
    inputs: {}
    outputs: {}
    metadata: {}
    retryStrategy:
      limit: '2'
    timeout: 600s
