metadata:
  generateName: collect-aorc-forcing-v1-
  namespace: workflows
spec:
  templates:
    - name: aorc-subset-huc
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: huc-to-shp
            template: huc-to-shp
            arguments:
              parameters:
                - name: artifact-path
                  value: '{{workflow.parameters.output_path}}'
                - name: hucs
                  value: '{{workflow.parameters.hucs}}'
        - - name: collect-aorc
            template: collect-aorc
            arguments:
              parameters:
                - name: start-date
                  value: '{{workflow.parameters.start-date}}'
                - name: end-date
                  value: '{{workflow.parameters.end-date}}'
                - name: artifact-path
                  value: '{{workflow.parameters.output_path}}'
                - name: aorc-secret
                  value: '{{workflow.parameters.aorc-secret}}'
        - - name: metadata-extractor
            template: metadata-extractor
            arguments:
              parameters:
                - name: artifact-path
                  value: '{{workflow.parameters.output_path}}'
    - name: huc-to-shp
      inputs:
        parameters:
          - name: artifact-path
          - name: hucs
      outputs:
        artifacts:
          - name: shape-results
            path: /output
            s3:
              endpoint: api.minio.cuahsi.io
              bucket: subsetter-outputs
              accessKeySecret:
                name: minio-credentials
                key: accessKey
              secretKeySecret:
                name: minio-credentials
                key: secretKey
              key: '{{inputs.parameters.artifact-path}}/shape.gz'
      metadata: {}
      container:
        name: ''
        image: us-central1-docker.pkg.dev/apps-320517/subsetter/huc-to-shp:0.0.4
        args:
          - '{{inputs.parameters.hucs}}'
          - /output/watershed.shp
        resources: {}

    - name: collect-aorc
      inputs:
        parameters:
          - name: start-date
          - name: end-date
          - name: artifact-path
          - name: aorc-secret
        artifacts:
          - name: shapefile-input
            path: /srv/shp-data
            s3:
              endpoint: api.minio.cuahsi.io
              bucket: subsetter-outputs
              accessKeySecret:
                name: minio-credentials
                key: accessKey
              secretKeySecret:
                name: minio-credentials
                key: secretKey
              key: '{{inputs.parameters.artifact-path}}/shape.gz'
      outputs:
        artifacts:
          - name: aorc-output-artifact
            path: /output
            s3:
              endpoint: api.minio.cuahsi.io
              bucket: subsetter-outputs
              accessKeySecret:
                name: minio-credentials
                key: accessKey
              secretKeySecret:
                name: minio-credentials
                key: secretKey
              key: '{{inputs.parameters.artifact-path}}/aorc_output.gz'
      metadata: {}
      container:
        image: us-central1-docker.pkg.dev/apps-320517/subsetter/aorc:0.0.2
        env:
          - name: KEY
            value: AKIATL6IACWUADAFYDMC
          - name: SECRET
            value: '{{inputs.parameters.aorc-secret}}'
          - name: BUCKET_URL
            value: s3://aorc-v1.1-zarr-1-year/
          - name: SHAPE_FILE
            value: /srv/shp-data/watershed.shp
          - name: START_DATE
            value: '{{inputs.parameters.start-date}}'
          - name: END_DATE
            value: '{{inputs.parameters.end-date}}'
          - name: OUTPUT_FILE
            value: /output/results.nc
          - name: N_WORKERS
            value: '2'
          - name: MEMORY_LIMIT
            value: 4GB
        command:
          - /bin/sh
          - '-c'
        args:
          - >-
            python /app/collect-aorc-forcing-v1.1.py
        ports:
          - containerPort: 8787
        resources:
          requests:
            cpu: '2'
            ephemeral-storage: 10Gi
            memory: 16Gi
    - name: metadata-extractor
      inputs:
        parameters:
          - name: artifact-path
        artifacts:
          - name: extractor-input
            path: /tmp/subset-data
            s3:
              endpoint: api.minio.cuahsi.io
              bucket: subsetter-outputs
              accessKeySecret:
                name: minio-credentials
                key: accessKey
              secretKeySecret:
                name: minio-credentials
                key: secretKey
              key: '{{inputs.parameters.artifact-path}}/aorc_output.gz'
      outputs:
        artifacts:
          - name: extractor-output
            path: /tmp/subset-data
            s3:
              endpoint: api.minio.cuahsi.io
              bucket: subsetter-outputs
              accessKeySecret:
                name: minio-credentials
                key: accessKey
              secretKeySecret:
                name: minio-credentials
                key: secretKey
              key: '{{inputs.parameters.artifact-path}}/all.gz'
      metadata: {}
      container:
        name: ''
        image: scootna/hsextract:0.1
        command:
          - /bin/sh
          - '-c'
        args:
          - >-
            python3 hsextract/main.py extract /tmp/subset-data && mv
            /tmp/subset-data/.hs /tmp/subset-data/hs
        resources: {}
  entrypoint: aorc-subset-huc
  arguments:
    parameters:
      - name: start-date
        value: '2020-01-01'
      - name: end-date
        value: '2020-01-2'
      - name: output_path
        value: qwerty
      - name: hucs
        value: 102600070103,102600070104,102600090205,102600050206,102600070102
      - name: aorc-secret
        value: changethis
  templateDefaults:
    inputs: {}
    outputs: {}
    metadata: {}
    retryStrategy:
      limit: '0'
    timeout: 600s

