metadata:
  name: collect-aorc-forcing-full-v1.1
  namespace: workflows
spec:
  templates:
    - name: aorc-subset-huc
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: huc-to-shp
            templateRef: 
              name: huc-to-shp
              template: huc-to-shp
            arguments:
              parameters:
                - name: artifact-path
                  value: '{{workflow.parameters.output_path}}'
                - name: hucs
                  value: '{{workflow.parameters.hucs}}'
        - - name: collect-aorc-forcing
            templateRef: 
              name: collect-aorc-forcing-v1.1
              template: collect-aorc
            arguments:
              parameters:
                - name: start-date
                  value: '{{workflow.parameters.start-date}}'
                - name: end-date
                  value: '{{workflow.parameters.end-date}}'
                - name: output-path
                  value: '{{workflow.parameters.output_path}}'
                - name: shape-file-path
                  value: '{{workflow.parameters.output_path}}/shape.gz'
                - name: aorc-secret
                  value: '{{workflow.parameters.aorc-secret}}'
        - - name: metadata-extraction
            templateRef: 
              name: metadata-extractor
              template: metadata-extractor
            arguments:
              parameters:
                - name: bucket
                  value: subsetter-outputs
                - name: path
                  value: '{{workflow.parameters.output_path}}/aorc_output.gz'
                - name: output-path
                  value: '{{workflow.parameters.output_path}}/metadata.gz'
  entrypoint: aorc-subset-huc
  arguments:
    parameters:
      - name: start-date
        value: '2020-01-01'
      - name: end-date
        value: '2020-01-2'
      - name: output_path
        value: sblack/templatetest
      - name: hucs
        value: 102600070103,102600070104,102600090205,102600050206,102600070102
      - name: aorc-secret
        value: changethis
  templateDefaults:
    inputs: {}
    outputs: {}
    metadata: {}
    retryStrategy:
      limit: '0'
    timeout: 600s

