metadata:
  name: nwm2-subset-minio
  namespace: workflows
spec:
  templates:
    - name: nwm2-subset-with-extraction-template
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: nwm2-subset-step-name
            template: nwm2-subset-template
            arguments:
              parameters:
                - name: y_south
                  value: '{{workflow.parameters.y_south}}'
                - name: x_west
                  value: '{{workflow.parameters.x_west}}'
                - name: y_north
                  value: '{{workflow.parameters.y_north}}'
                - name: x_east
                  value: '{{workflow.parameters.x_east}}'
                - name: output-path
                  value: '{{workflow.parameters.output-path}}'
                - name: output-bucket
                  value: '{{workflow.parameters.output-bucket}}'
        - - name: metadata-extractor
            template: metadata-extractor-template
            arguments:
              parameters:
                - name: output-path
                  value: '{{workflow.parameters.output-path}}'
                - name: output-bucket
                  value: '{{workflow.parameters.output-bucket}}'
    - name: nwm2-subset-template
      inputs:
        parameters:
          - name: y_south
          - name: x_west
          - name: y_north
          - name: x_east
          - name: output-path
          - name: output-bucket
        artifacts:
          - name: nwm2-input-data
            path: /srv/domain
            s3:
              endpoint: api.minio.cuahsi.io
              bucket: subsetter-static-input
              accessKeySecret:
                name: minio-credentials
                key: accessKey
              secretKeySecret:
                name: minio-credentials
                key: secretKey
              key: nwm.v2.0.0.gz
      outputs:
        artifacts:
          - name: subset-results
            path: /srv/output
            s3:
              endpoint: api.minio.cuahsi.io
              bucket: '{{inputs.parameters.output-bucket}}'
              accessKeySecret:
                name: minio-credentials
                key: accessKey
              secretKeySecret:
                name: minio-credentials
                key: secretKey
              key: '{{inputs.parameters.output-path}}/subset.gz'
      metadata: {}
      container:
        name: ''
        image: us-central1-docker.pkg.dev/apps-320517/subsetter/nwm2:0.0.1
        command:
          - python
          - '-u'
          - entry.py
        args:
          - '{{inputs.parameters.y_south}}'
          - '{{inputs.parameters.x_west}}'
          - '{{inputs.parameters.y_north}}'
          - '{{inputs.parameters.x_east}}'
          - /srv/domain
          - /srv/output
        resources:
          requests:
            cpu: '1'
            ephemeral-storage: 2Gi
            memory: 1Gi
    - name: metadata-extractor-template
      inputs:
        parameters:
          - name: output-path
          - name: output-bucket
        artifacts:
          - name: extractor-input
            path: /tmp/subset-data
            s3:
              endpoint: api.minio.cuahsi.io
              bucket: '{{inputs.parameters.output-bucket}}'
              accessKeySecret:
                name: minio-credentials
                key: accessKey
              secretKeySecret:
                name: minio-credentials
                key: secretKey
              key: '{{inputs.parameters.output-path}}/subset.gz'
      outputs:
        artifacts:
          - name: extractor-output
            path: /tmp/subset-data
            s3:
              endpoint: api.minio.cuahsi.io
              bucket: '{{inputs.parameters.output-bucket}}'
              accessKeySecret:
                name: minio-credentials
                key: accessKey
              secretKeySecret:
                name: minio-credentials
                key: secretKey
              key: '{{inputs.parameters.output-path}}/all.gz'
      metadata: {}
      container:
        name: ''
        image: scootna/hsextract:0.1
        command:
          - /bin/sh
          - '-c'
        args:
          - >-
            python3 hsextract/main.py extract /tmp/subset-data && mv
            /tmp/subset-data/.hs /tmp/subset-data/hs
        resources:
          requests:
            cpu: '1'
            ephemeral-storage: 2Gi
            memory: 1Gi
  entrypoint: nwm2-subset-with-extraction-template
  arguments:
    parameters:
      - name: y_south
        value: '382582.18746'
      - name: x_west
        value: '1720355.72762'
      - name: y_north
        value: '367584.8784'
      - name: x_east
        value: '1734488.4526'
      - name: output-path
        value: 'asdf'
      - name: output-bucket
        value: 'subsetter-outputs'
  templateDefaults:
    inputs: {}
    outputs: {}
    metadata: {}
