metadata:
  name: parflow-subset-v1-by-huc-minio
  namespace: workflows
spec:
  templates:
    - name: parflow-subset-huc
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: huc-to-shp
            template: huc-to-shp
            arguments:
              parameters:
                - name: output-path
                  value: '{{workflow.parameters.output-path}}'
                - name: output-bucket
                  value: '{{workflow.parameters.output-bucket}}'
                - name: hucs
                  value: '{{workflow.parameters.hucs}}'
        - - name: subset-parflow
            template: parflow-subset-v1
            arguments:
              parameters:
                - name: label
                  value: '{{workflow.parameters.label}}'
                - name: output-path
                  value: '{{workflow.parameters.output-path}}'
                - name: output-bucket
                  value: '{{workflow.parameters.output-bucket}}'
        - - name: metadata-extractor
            template: metadata-extractor
            arguments:
              parameters:
                - name: output-path
                  value: '{{workflow.parameters.output-path}}'
                - name: output-bucket
                  value: '{{workflow.parameters.output-bucket}}'
    - name: huc-to-shp
      inputs:
        parameters:
          - name: output-path
          - name: output-bucket
          - name: hucs
      outputs:
        artifacts:
          - name: shape-results
            path: /output
            s3:
              endpoint: api.minio.cuahsi.io
              bucket: '{{inputs.parameters.output-bucket}}'
              accessKeySecret:
                name: minio-credentials
                key: accessKey
              secretKeySecret:
                name: minio-credentials
                key: secretKey
              key: '{{inputs.parameters.output-path}}/shape.gz'
      metadata: {}
      container:
        name: ''
        image: us-central1-docker.pkg.dev/apps-320517/subsetter/huc-to-shp:0.0.4
        args:
          - '{{inputs.parameters.hucs}}'
          - /output/watershed.shp
        resources: {}
    - name: parflow-subset-v1
      inputs:
        parameters:
          - name: label
          - name: output-path
          - name: output-bucket
        artifacts:
          - name: pfinput-data
            path: /srv/input
            s3:
              endpoint: api.minio.cuahsi.io
              bucket: subsetter-static-input
              accessKeySecret:
                name: minio-credentials
                key: accessKey
              secretKeySecret:
                name: minio-credentials
                key: secretKey
              key: pfconus.v1.0.gz
          - name: shape-input-data
            path: /srv/shape
            s3:
              endpoint: api.minio.cuahsi.io
              bucket: '{{inputs.parameters.output-bucket}}'
              accessKeySecret:
                name: minio-credentials
                key: accessKey
              secretKeySecret:
                name: minio-credentials
                key: secretKey
              key: '{{inputs.parameters.output-path}}/shape.gz'
      outputs:
        artifacts:
          - name: subset-results
            path: /srv/shape
            s3:
              endpoint: api.minio.cuahsi.io
              bucket: '{{inputs.parameters.output-bucket}}'
              accessKeySecret:
                name: minio-credentials
                key: accessKey
              secretKeySecret:
                name: minio-credentials
                key: secretKey
              key: '{{inputs.parameters.output-path}}/subset.gz'
      metadata: {}
      container:
        name: ''
        image: cuahsi/parflow-subset-argo:v1
        command:
          - python
          - '-u'
          - entry.py
        args:
          - '{{inputs.parameters.label}}'
          - /srv/shape/watershed.shp
          - /srv/input
          - /srv/shape
        resources:
          limits:
            cpu: '2'
            ephemeral-storage: 2Gi
            memory: 1Gi
          requests:
            cpu: '1'
            ephemeral-storage: 1Gi
            memory: 1Gi
    - name: metadata-extractor
      inputs:
        parameters:
          - name: output-path
          - name: output-bucket
        artifacts:
          - name: extractor-input
            path: /tmp/subset-data
            s3:
              endpoint: api.minio.cuahsi.io
              bucket: '{{inputs.parameters.output-bucket}}'
              accessKeySecret:
                name: minio-credentials
                key: accessKey
              secretKeySecret:
                name: minio-credentials
                key: secretKey
              key: '{{inputs.parameters.output-path}}/subset.gz'
      outputs:
        artifacts:
          - name: extractor-output
            path: /tmp/subset-data
            s3:
              endpoint: api.minio.cuahsi.io
              bucket: '{{inputs.parameters.output-bucket}}'
              accessKeySecret:
                name: minio-credentials
                key: accessKey
              secretKeySecret:
                name: minio-credentials
                key: secretKey
              key: '{{inputs.parameters.output-path}}/all.gz'
      metadata: {}
      container:
        name: ''
        image: scootna/hsextract:0.1
        command:
          - /bin/sh
          - '-c'
        args:
          - >-
            python3 hsextract/main.py extract /tmp/subset-data && mv
            /tmp/subset-data/.hs /tmp/subset-data/hs
        resources: {}
  entrypoint: parflow-subset-huc
  arguments:
    parameters:
      - name: label
        value: pf-subset-job
      - name: output-path
        value: abc123
      - name: output-bucket
        value: subsetter-outputs
      - name: hucs
        value: 102600070103,102600070104,102600090205,102600050206,102600070102
  templateDefaults:
    inputs: {}
    outputs: {}
    metadata: {}
    retryStrategy:
      limit: '2'
    timeout: 600s
