apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: parflow-subset-v1-by-huc-minio
  generateName: parflow-subset-v1-by-huc-minio-
  namespace: workflows
spec:
  entrypoint: parflow-subset-huc
  templateDefaults:
    timeout: 600s  
    retryStrategy:
      limit: "2"
  arguments:
    parameters:
    - name: label
      value: pf-subset-job
    - name: job-id
      value: abc123
    - name: hucs
      value: 102600070103,102600070104,102600090205,102600050206,102600070102
      
  templates:
  - name: parflow-subset-huc
    steps:
    - - name: huc-to-shp
        template: huc-to-shp
        arguments:
          parameters:
          - name: artifact-path
            value: 'parflow/{{workflow.parameters.job-id}}'
          - name: hucs
            value: "{{workflow.parameters.hucs}}"
    - - name: subset-parflow
        template: parflow-subset-v1
        arguments:
          parameters:
          - name: label
            value: "{{workflow.parameters.label}}"
          - name: artifact-path
            value: 'parflow/{{workflow.parameters.job-id}}'
    - - name: metadata-extractor
        template: metadata-extractor
        arguments:
          parameters:
          - name: artifact-path
            value: 'parflow/{{workflow.parameters.job-id}}'

  - name: huc-to-shp
    inputs:
      parameters:
        - name: artifact-path
        - name: hucs
    outputs:
      artifacts:
        - name: shape-results
          path: /output
          s3:
            bucket: subsetter-outputs
            key: "{{inputs.parameters.artifact-path}}/shape.gz"
            endpoint: api.minio.cuahsi.io
            accessKeySecret:
              name: minio-credentials
              key: accessKey
            secretKeySecret:
              name: minio-credentials
              key: secretKey
    container:
      image: us-central1-docker.pkg.dev/apps-320517/subsetter/huc-to-shp:0.0.4
      args: ["{{inputs.parameters.hucs}}", "/output/watershed.shp"]

  - name: parflow-subset-v1
    inputs:
      parameters:
        - name: label
        - name: artifact-path
      artifacts:
        - name: pfinput-data
          path: /srv/input
          s3:
            bucket: subsetter-static-input
            key: pfconus.v1.0
            endpoint: api.minio.cuahsi.io
            accessKeySecret:
              name: minio-credentials
              key: accessKey
            secretKeySecret:
              name: minio-credentials
              key: secretKey
        - name: shape-input-data
          path: /srv/shape
          s3:
            bucket: subsetter-outputs
            key: "{{inputs.parameters.artifact-path}}/shape.gz"
            endpoint: api.minio.cuahsi.io
            accessKeySecret:
              name: minio-credentials
              key: accessKey
            secretKeySecret:
              name: minio-credentials
              key: secretKey
    container:
      image: cuahsi/parflow-subset-argo:v1
      resources:
        requests:
          memory: "1Gi"
          cpu: 1
          ephemeral-storage: "1Gi"
        limits:
          memory: "1Gi"
          cpu: 2
          ephemeral-storage: "2Gi"
      command: ["python", "-u", "entry.py"]
      args: ["{{inputs.parameters.label}}",
             "/srv/shape/watershed.shp",
             "/srv/input",
             "/srv/shape"]
    outputs:
      artifacts:
        - name: subset-results
          path: /srv/shape
          s3:
            bucket: subsetter-outputs
            key: "{{inputs.parameters.artifact-path}}/subset.gz"
            endpoint: api.minio.cuahsi.io
            accessKeySecret:
              name: minio-credentials
              key: accessKey
            secretKeySecret:
              name: minio-credentials
              key: secretKey

  - name: metadata-extractor
    inputs:
      parameters:
        - name: artifact-path
      artifacts:
        - name: extractor-input
          path: /tmp/subset-data
          s3:
            bucket: subsetter-outputs
            key: "{{inputs.parameters.artifact-path}}/subset.gz"
            endpoint: api.minio.cuahsi.io
            accessKeySecret:
              name: minio-credentials
              key: accessKey
            secretKeySecret:
              name: minio-credentials
              key: secretKey
    outputs:
      artifacts:
        - name: extractor-output
          path: /tmp/subset-data
          s3:
            bucket: subsetter-outputs
            key: "{{inputs.parameters.artifact-path}}/all.gz"
            endpoint: api.minio.cuahsi.io
            accessKeySecret:
              name: minio-credentials
              key: accessKey
            secretKeySecret:
              name: minio-credentials
              key: secretKey
    metadata: {}
    container:
      name: ''
      image: scootna/hsextract:0.1
      command:
        - /bin/sh
        - '-c'
      args:
        - >-
          python3 hsextract/main.py extract /tmp/subset-data && mv /tmp/subset-data/.hs /tmp/subset-data/hs
      resources: {}