apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: compress-dataset-
  namespace: workflows
spec:
  entrypoint: compress-dataset
  templates:
  - name: compress-dataset
    inputs:
      artifacts:
        - name: pfconus-data-uncompressed
          path: /mnt/input
          gcs:
            bucket: subsetter-static-input
            key: "nwm.v2.0.0"
            serviceAccountKeySecret:
              name: my-gcs-creds
              key: serviceAccountKey
    script:
      image: scootna/hsextract:0.1
      command: ["sh", "-c"]
      args: ["ls -la"]
    outputs:
      artifacts:
        - name: pfconus-data-compressed
          path: /mnt/input
          s3:
            bucket: subsetter-static-input
            key: "nwm.v2.0.0.gz"
            endpoint: api.minio.cuahsi.io
            accessKeySecret:
              name: minio-credentials
              key: accessKey
            secretKeySecret:
              name: minio-credentials
              key: secretKey