metadata:
  name: nwm2-subset-minio
  namespace: workflows
spec:
  templates:
    - name: nwm2-subset-with-extraction-template
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: nwm2-subset-step-name
            template: nwm2-subset-template
            arguments:
              parameters:
                - name: y_south
                  value: '{{workflow.parameters.y_south}}'
                - name: x_west
                  value: '{{workflow.parameters.x_west}}'
                - name: y_north
                  value: '{{workflow.parameters.y_north}}'
                - name: x_east
                  value: '{{workflow.parameters.x_east}}'
                - name: output-path
                  value: '{{workflow.parameters.output-path}}'
                - name: output-bucket
                  value: '{{workflow.parameters.output-bucket}}'
        - - name: metadata-extraction
            templateRef:
              name: metadata-extractor
              template: metadata-extractor
            arguments:
              parameters:
                - name: bucket
                  value: '{{workflow.parameters.output-bucket}}'
                - name: input-path
                  value: '{{workflow.parameters.output-path}}'
                - name: output-path
                  value: '{{workflow.parameters.output-path}}_metadata.tgz'
    - name: nwm2-subset-template
      inputs:
        parameters:
          - name: y_south
          - name: x_west
          - name: y_north
          - name: x_east
          - name: output-path
          - name: output-bucket
      outputs:
        artifacts:
          - name: subset-results
            path: /srv/output
            s3:
              endpoint: api.minio.cuahsi.io
              bucket: '{{inputs.parameters.output-bucket}}'
              accessKeySecret:
                name: minio-credentials
                key: accessKey
              secretKeySecret:
                name: minio-credentials
                key: secretKey
              key: '{{inputs.parameters.output-path}}'
      metadata: {}
      container:
        name: ''
        image: us-central1-docker.pkg.dev/apps-320517/subsetter/nwm2:0.0.1
        command:
          - python
          - '-u'
          - entry.py
        args:
          - '{{inputs.parameters.y_south}}'
          - '{{inputs.parameters.x_west}}'
          - '{{inputs.parameters.y_north}}'
          - '{{inputs.parameters.x_east}}'
          - /srv/domain/nwm.v2.0.0/input
          - /srv/output
        resources:
          requests:
            cpu: '1'
            ephemeral-storage: 2Gi
            memory: 1Gi
        volumeMounts:
          - name: subsetter-data-volume
            mountPath: /srv/domain
  entrypoint: nwm2-subset-with-extraction-template
  arguments:
    parameters:
      - name: y_south
        value: '382582.18746'
      - name: x_west
        value: '1720355.72762'
      - name: y_north
        value: '367584.8784'
      - name: x_east
        value: '1734488.4526'
      - name: output-path
        value: 'asdf'
      - name: output-bucket
        value: 'subsetter-outputs'
  volumes:
    - name: subsetter-data-volume
      persistentVolumeClaim:
        claimName: subset-accelerator
  templateDefaults:
    inputs: {}
    outputs: {}
    metadata: {}
