apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: transfer-gcp-minio-
  namespace: workflows
spec:
  entrypoint: transfer-gcp-minio
  templateDefaults:
    timeout: 600s  
    retryStrategy:
      limit: "2"
      
  templates:
  - name: transfer-gcp-minio-template
    steps:
    - - name: transfer-gcp-minio
        template: transfer-gcp-minio

  - name: transfer-gcp-minio
    container:
      image: minio/mc
      command: ["sh", "-c"]
      args: ["mc alias set cuahsi https://api.minio.cuahsi.io KKlLAx31Ermq0Wizpdl1 CQcCaOZG5uG5SMoSHjXg3wHyIhWWEAtqm6gQgxIN && mc alias set gcp https://storage.googleapis.com GOOG1E2CMGCFE2IM5XW26OJ3VIL7M34YIBJOXDKAAFAN2HTBGDSDGPXRH4V4J kq/zDsGdkUyp3wIzanTeQCM8Y4LHn4dCSVm5ZMWg && mc cp --recursive gcp/subsetter-static-input/nwm.v1.2.4/ cuahsi/subsetter-static-input/nwmv124"]