name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - gdal
  - basemap
  - pip:
    - aiohttp
    - aioredis
    - asyncio
    - hs-restclient
    - multiprocessing-logging
    - pfio
    - redis
    - requests
    - requests-oauthlib
    - requests-toolbelt
    - shapely
    - python-cas
    - matplotlib
    - numpy
    - pandas
    - python-dateutil
    - scipy
    - tornado
    - xarray
    - pyproj
    - pyshp
    - pytz
    - netcdf4
    - pyproj
    - h5py
    - pysqlite3
    - geos
    - ogr
    - osr
